
# Input file for model training

nGraphConvolutionLayers: 2 # Number of graph convolutional layers
nNodeNeurons: 78 # Number of node neurons for GNN
nEdgeNeurons: 107 # Number of edge neurons for GNN
dropoutGNN: 0.001 # Dropout in graph convolutional layers
momentumBatchNorm: 0.1 # Batch normalization in graph convolutional layers

nSharedLayers: 2  # Number of layers in shared core
nTargetSpecificLayers: 2 # Number of layers in target specific core
nShared: [100, 50] # Number of neurons in shared core
nTarget: [50, 10] # Number of neurons in target specific core
dropoutShared: [0.25, 0.15] # Dropout in shared core
dropoutTarget: [0.15, 0.15]
 # Dropout in target specific core

# Weights for weighted cost function
w1: 1.90
w2: 1.56
w3: 3.31
w4: 5.09
w5: 5.11

# Activation function
ActivationFunction: "Tanh" #"Tanh"

nEpochs: 1 #np.iinfo(np.int32). # Number of epochs
nBatch: 32 # Ba15h size
nCheckpoint: 1 # Checkpoint frequency
randomSeed: 15 # Random seed
#nTrainMaxEntries: 1500 # Number of training samples to use
#nValMaxEntries: 300 # Number of validation examples to  use

learningRate: 0.0000925 #0.0000924993113995373 #0.0001 #5e-4

weightedCostFunction: True # Include weighted cost function
L2Regularization: 0.005 # L2 regularization coefficient

# the following command specifies if the model.state_dict() and optimizer.state_dict() are to be loaded
# from a checkpoint file from a previous run 
loadModel: False
loadOptimizer: False
StateDictFileName: '/Users/abigailteitgen/Dropbox/Postdoc/AMES_GNN_MTL_Network/AMES/output/checkpoint_epoch_1.pt'

# warmStart: "GraphPotential-nn-2gcl-2fcl-31102023-173821.tar"

useMolecularDescriptors: False # Use molecular features instead of graphs for comparison to original MTL paper

GNNExplainerAnalysis: False # Run GNNExplainer analysis after training

callbacks: 
   earlyStopping:
      patience: 10 #1000
      min_delta: 1.0e-5 #5e-4
   LRScheduler:
      patience: 1
      min_lr: 1.0e-8
      factor: 0.1
   UserStopping:

descriptionText: 'No data transformation'

# where the graph data-base resides
database: '/Users/abigailteitgen/Dropbox/Postdoc/AMES_GNN_MTL_Network/GraphDataBase_AMES'

# file with molecular data
data_file: '/Users/abigailteitgen/Dropbox/Postdoc/AMES_GNN_MTL_Network/AMES/data.csv'

# transformData: std

