
# Input file for model training

nGraphConvolutionLayers: 2 # Number of graph convolutional layers
nNodeNeurons: 278 # Number of node neurons for GNN
nEdgeNeurons: 300 # Number of edge neurons for GNN
dropoutGNN: 0.0366 # Dropout in graph convolutional layers
momentumBatchNormGNN: 0.0776 # Batch normalization in graph convolutional layers

nSharedLayers: 2 # Number of layers in shared core
nTargetSpecificLayers: 1 # Number of layers in target specific core
nShared: [271, 87] # Number of neurons in shared core
nTarget: [107] # Number of neurons in target specific core
dropoutShared: [0.4221, 0.1147] # Dropout in shared core
dropoutTarget: [0.3156] # Dropout in target specific core
momentumBatchNormShared: 0.0776 # Batch normalization in shared core
momentumBatchNormTarget: 0.0776 # Batch normalization in target specific core

# Weights for weighted cost function
w1: 3.394
w2: 5.988
w3: 5.476
w4: 1.008
w5: 1.080

# Activation function
ActivationFunction: "Tanh" #"Tanh"

nEpochs: 1 #np.iinfo(np.int32). # Number of epochs
nBatch: 32 # Batch size
nCheckpoint: 10 # Checkpoint frequency
randomSeed: 42 # Random seed
nTrainMaxEntries: 1500 # Number of training samples to use
nValMaxEntries: 300 # Number of validation examples to  use

learningRate: 0.0011 #0.0000924993113995373 #0.0001 #5e-4

weightedCostFunction: True # Include weighted cost function
L2Regularization: 0.005 # L2 regularization coefficient

# the following command specifies if the model.state_dict() and optimizer.state_dict() are to be loaded
# from a checkpoint file from a previous run 
loadModel: False
loadOptimizer: False
#StateDictFileName: "GraphPotential-nn-2gcl-2fcl-05122023-135254.tar"

# warmStart: "GraphPotential-nn-2gcl-2fcl-31102023-173821.tar"

useMolecularDescriptors: False # Use molecular features instead of graphs for comparison to original MTL paper

GNNExplainerAnalysis: False # Run GNNExplainer analysis after training

callbacks: 
   earlyStopping:
      patience: 10 #1000
      min_delta: 1.0e-5 #5e-4
   LRScheduler:
      patience: 1
      min_lr: 1.0e-8
      factor: 0.1
   UserStopping:

descriptionText: 'No data transformation'

# where the graph data-base resides
database: '/Users/abigailteitgen/Dropbox/Postdoc/AMES_GNN_MTL_Network/GraphDataBase_AMES'

# file with molecular data
data_file: '/Users/abigailteitgen/Dropbox/Postdoc/AMES_GNN_MTL_Network/AMES/data.csv'

# transformData: std

